apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-app
            port:
              number: {{ .Values.demo.env.PORT }}
